# Generated by Django 3.2.6 on 2022-02-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220225_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocking',
            name='count_time',
            field=models.IntegerField(default=0),
        ),
    ]
